a1_gazebo:
    A1_controller:
        type: song_ros_control/A1Controller
        joint_name_list:
          ["FR_hip_joint", "FL_hip_joint", "RR_hip_joint", "RL_hip_joint", "FR_thigh_joint", "FL_thigh_joint", "RR_thigh_joint", "RL_thigh_joint", "FR_calf_joint", "FL_calf_joint", "RR_calf_joint", "RL_calf_joint"]